"""Cloudinary client — hosting for AI-generated media (images and VEO videos).

SECURITY: ``CLOUDINARY_API_SECRET`` is a **server-only** credential. It is used
here to sign uploads and is never returned to clients or embedded in any
response. The frontend only ever receives the resulting ``secure_url`` /
``public_id``. Uploads are always signed (never unsigned/browser-preset).

Generated bytes (e.g. an image from Imagen) or a remote provider URL (e.g. a VEO
result URL) are pushed to Cloudinary, which becomes the durable CDN origin we
persist and serve.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional, Union

from app.core.config import settings
from app.core.exceptions import ProviderError, ServiceUnavailableError
from app.core.logging import get_logger

logger = get_logger(__name__)

_configured = False


@dataclass
class UploadedAsset:
    url: str
    public_id: str
    resource_type: str = "image"
    format: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None
    duration: Optional[float] = None
    bytes: Optional[int] = None

    def as_dict(self) -> dict[str, Any]:
        return {
            "url": self.url,
            "public_id": self.public_id,
            "resource_type": self.resource_type,
            "format": self.format,
            "width": self.width,
            "height": self.height,
            "duration": self.duration,
            "bytes": self.bytes,
        }


def _ensure_configured() -> None:
    """Configure the Cloudinary SDK once from server settings."""
    global _configured
    if _configured:
        return
    if not settings.cloudinary_configured:
        raise ServiceUnavailableError(
            "Media hosting is not configured (CLOUDINARY_* env vars missing)."
        )
    try:
        import cloudinary
    except ImportError as exc:  # pragma: no cover - dependency guard
        raise ServiceUnavailableError("Media hosting is unavailable (cloudinary not installed).") from exc

    cloudinary.config(
        cloud_name=settings.cloudinary_cloud_name,
        api_key=settings.cloudinary_api_key,
        api_secret=settings.cloudinary_api_secret,
        secure=True,
    )
    _configured = True


def _result_to_asset(result: dict[str, Any], default_type: str) -> UploadedAsset:
    return UploadedAsset(
        url=result.get("secure_url") or result.get("url") or "",
        public_id=result.get("public_id") or "",
        resource_type=result.get("resource_type") or default_type,
        format=result.get("format"),
        width=result.get("width"),
        height=result.get("height"),
        duration=result.get("duration"),
        bytes=result.get("bytes"),
    )


def upload_media(
    source: Union[bytes, str],
    *,
    resource_type: str = "image",
    folder: Optional[str] = None,
    public_id: Optional[str] = None,
    context: Optional[dict[str, str]] = None,
) -> UploadedAsset:
    """Upload media to Cloudinary.

    ``source`` may be raw bytes (generated media) or a string URL (a provider
    result URL Cloudinary will fetch). ``resource_type`` is ``image`` or
    ``video``. Uploads are signed with the server API secret.
    """
    _ensure_configured()
    import cloudinary.uploader

    options: dict[str, Any] = {
        "resource_type": resource_type,
        "folder": folder or settings.cloudinary_upload_folder,
        "overwrite": False,
        # Signed upload: no unsigned preset. The SDK signs with the API secret.
    }
    if public_id:
        options["public_id"] = public_id
    if context:
        options["context"] = context

    try:
        result = cloudinary.uploader.upload(source, **options)
    except Exception as exc:  # cloudinary raises its own Error types
        logger.warning("cloudinary upload failed: %s", type(exc).__name__)
        raise ProviderError("Failed to store the generated media.") from exc

    return _result_to_asset(result, resource_type)


def upload_document(
    data: bytes,
    *,
    user_id: str,
    filename: str,
    content_type: str,
) -> UploadedAsset:
    """Upload a raw study document (PDF / TXT / MD) to Cloudinary.

    Stored under ``lumina/documents/<user_id>/`` with ``resource_type="raw"``
    so the file is served as-is. The returned ``url`` (secure_url) is stored in
    ``documents.file_key``; ``public_id`` is stored separately and used for
    deletion. The API secret signs this upload — never exposed to the client.
    """
    _ensure_configured()
    import cloudinary.uploader

    folder = f"{settings.cloudinary_upload_folder}/documents/{user_id}"
    options: dict[str, Any] = {
        "resource_type": "raw",
        "folder": folder,
        "overwrite": False,
        "use_filename": True,
        "unique_filename": True,
        "context": {"content_type": content_type},
    }

    try:
        result = cloudinary.uploader.upload(data, **options)
    except Exception as exc:
        logger.warning("cloudinary document upload failed: %s", type(exc).__name__)
        raise ProviderError("Failed to store the uploaded document.") from exc

    asset = _result_to_asset(result, "raw")
    logger.info(
        "cloudinary document upload ok: public_id=%s bytes=%s",
        asset.public_id,
        asset.bytes,
    )
    return asset


def download_bytes(url: str) -> bytes:
    """Fetch raw bytes from a Cloudinary secure_url for the ingestion pipeline.

    The URL was stored in ``documents.file_key`` at upload time. Uses a
    generous 60-second timeout because document files can be up to 50 MB.
    """
    import httpx

    try:
        with httpx.Client(timeout=60.0) as client:
            resp = client.get(url)
    except httpx.HTTPError as exc:
        logger.warning("cloudinary download transport error: %s", exc)
        raise ProviderError("Failed to download document from storage.") from exc

    if resp.status_code >= 400:
        logger.warning(
            "cloudinary download returned HTTP %s for url ending ...%s",
            resp.status_code,
            url[-40:],
        )
        raise ProviderError("Could not retrieve the stored document.")

    return resp.content


def delete_media(public_id: str, *, resource_type: str = "image") -> None:
    """Best-effort deletion of a hosted asset."""
    _ensure_configured()
    import cloudinary.uploader

    try:
        cloudinary.uploader.destroy(public_id, resource_type=resource_type)
    except Exception as exc:
        logger.warning("cloudinary destroy failed: %s", type(exc).__name__)


def delete_document(public_id: str) -> None:
    """Best-effort deletion of a hosted document."""
    delete_media(public_id, resource_type="raw")
